### ISSUE TITLE
Superfluous `All rights reserved.` phrase in SPDX-FileCopyrightText

### ISSUE THREAD

**Issue by bernhardreiter** [org-metaeffekt/metaeffekt-universe#1]
https://github.com/org-metaeffekt/metaeffekt-universe/blob/e6fdfbfbf80009c4721185659274f1dee999864e/src/main/resources/ae-universe/%5B3%5D/%5B38%5D/389-Directory-Server-Exception.yaml#L2-L3

The `All  rights reserved.` sentence does not make sense if this is marked as `CC-BY-4.0`, does it?

Besides that `CC-BY-4.0` already gives out some rights, it is not necessary to claim rights with a phrase like this anymore, since 2000 it is considered outdated, see https://en.wikipedia.org/wiki/All_rights_reserved#Obsolescence (even before it wasn't considered necessary by everyone).

**Comment by karsten-klein** [comment]
Thanks for the hint. We however would like to stick to this common convention to indicate and emphasis our copyright ownership. The "All rights reserved." shall be part of the attribution when making use the provided data.
