### ISSUE TITLE
There is an alternative name to GPL-2.0-or-later that is not unambiguous

### ISSUE THREAD

**Issue by maxhbr** [org-metaeffekt/metaeffekt-universe#2]
Hey, I am trying to understand your data. 

In the `alternativeNames` of `GNU-General-Public-License-2.0-(or-any-later-version)` there is a line that matches multiple versions of GPL. Is that expected or a bug? 

https://github.com/org-metaeffekt/metaeffekt-universe/blob/7a16e44f459cd8e24520e6858d32d2c5cfc17871/src/main/resources/ae-universe/%5Bg%5D/%5Bgn%5D/GNU-General-Public-License-2.0-(or-any-later-version).yaml#L16

**Comment by maxhbr** [comment]
Also the `otherId` `"osi:GPL-2.0"` appears in multiple licenses that are not the same. So my assumption is that `otherIds` are also not meant to be unambiguous?

**Comment by karsten-klein** [comment]
You are absolutely right. I moved the "alternativeName" to GNU-General-Public-License-(undefined).yaml and removed the wrong otherId.

Om otherIds we plan to implement consistency checks for identifying duplicates and disambiguate.
