### ISSUE TITLE
Unallowed escaping in strings

### ISSUE THREAD

**Issue by maxhbr** [org-metaeffekt/metaeffekt-universe#3]
Hey,

when browsing through your data I found the following regular expressions which contain `\.` but probably should be `\\.` to make them valid yaml:

https://github.com/org-metaeffekt/metaeffekt-universe/blob/88af18b01d883015e5aa185ad08bf5acb44952f9/src/main/resources/ae-universe/%5Bg%5D/%5Bgn%5D/GNU-Library-General-Public-License-2.0.yaml#L15

**Comment by karsten-klein** [comment]
Fixed.

**Comment by karsten-klein** [comment]
Escaped as proposed.

**Comment by maxhbr** [comment]
Thanks!
